name: 'Assign Random Reviewers' # ì›Œí¬í”Œë¡œìš° ì´ë¦„

on:
  pull_request:
    types: [opened, reopened, ready_for_review] # PR ìƒì„±, ì¬ê°œ, ë¦¬ë·° ì¤€ë¹„ ì‹œ íŠ¸ë¦¬ê±°

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # PRì— ë¦¬ë·°ì–´ë¥¼ í• ë‹¹í•˜ê¸° ìœ„í•´ í•„ìš”
    
    steps:
      - name: ğŸƒ PR ì‘ì„±ìë¥¼ ì œì™¸í•˜ê³  ëœë¤ ë¦¬ë·°ì–´ í• ë‹¹
        uses: ihs7/action-reviewer-roulette@v1 # ì‚¬ìš©í•  ì•¡ì…˜, kentaro-m/auto-assign-actionë„ ê°€ëŠ¥
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number-of-reviewers: 2
          
          # ğŸš¨ ${{ github.actor }}ë¥¼ ì‚¬ìš©í•˜ì—¬ PR ì‘ì„±ìë¥¼ ì œì™¸í•©ë‹ˆë‹¤.
          excluded-reviewers: ${{ github.actor }}
